apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - secretRef:
                name: secret-dev
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql
            - mountPath: /docker-entrypoint-initdb.d
              name: init-script
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: bdd-pvc
        - name: init-script
          configMap:
            name: postgres-config