apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdd-pv
  labels:
    app: postgres 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/postgres-storage