apiVersion: v1
kind: PersistentVolume
metadata:
  name: bdd-pv
  labels:
    type: local
    app: postgres 
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/mnt/data/"