apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  clusterIP: 10.96.1.2
  ipFamilies:
  - IPv4
  ports:
  - name: postgres
    port: 5432
    nodePort: 30432
  type: NodePort
  selector:
    app: postgres
